### PR TITLE
Jvmahon patch 1

### PR DESCRIPTION
**Pull request by jvmahon**

### CODE REVIEW

**Comment by jonnyhk** [comment]
Hello

I'm not sure if this is the correct place to post but I give it a try :)

image
Node 24 Z-Wave Aeon

How to get this into Homebridge ?

**Comment by jonnyhk** [comment]
image

**Comment by jonnyhk** [comment]
OK
Thanks for helping :)I'm new into homebridge but have been using Homeseer for many year...Missing some trending on mobil device ..

Regards/ Med vennlig hilsen  Jonny Kristiansen IWocs engineer jonnyitalia@yahoo.comNO mob   : +47 4133 0777
 

    On Thursday, April 16, 2020, 04:45:38 AM GMT+2, jvmahon <notifications@github.com> wrote:  
 
 
You can view, comment on, or merge this pull request online at:

  https://github.com/jvmahon/Homebridge-HomeSeer4/pull/59

Commit Summary
   
   - Add files via upload
   - Update package.json
   - Add files via upload
   - Add files via upload
   - Add files via upload
   - Add files via upload
   - Add files via upload
   - Add files via upload
   - Add files via upload
   - Use fetch instead of request-promise-native
   - Add files via upload
   - Update package.json
   - Update package.json
   - Add files via upload

File Changes
   
   -  M config/All Configuration Parameters.js (166) 
   -  M index.js (12) 
   -  M lib/DeviceDefaults.js (14) 
   -  M lib/HomeKitDeviceSetup.js (51) 
   -  M lib/HomeSeerSystemObject.js (54) 
   -  M lib/HomeSeerUtilities.js (107) 
   -  M lib/Sensor Setup.js (73) 
   -  M lib/Setup Listener.js (8) 
   -  M lib/ThermostatSetup.js (11) 
   -  M package.json (15) 

Patch Links:
   
   - https://github.com/jvmahon/Homebridge-HomeSeer4/pull/59.patch
   - https://github.com/jvmahon/Homebridge-HomeSeer4/pull/59.diff

**Comment by jvmahon** [comment]
Please raise the issue in the "issues" section.

For your specific problem, the first thing you will need to know is the device reference number for each of the functions. If you don't know how to find that, begin by reading Section B here:
https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file

But based on your image, above, it looks like you found the ID "227" for the volts function.

I've just updated the Wiki section on this, so look here:

Thttps://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Energy-Meters

If you need further help, please open a new issue in the "Issues" section.

Best regards,
Jim

**Pull request merged**
